### ISSUE TITLE
Adding github actions to test docker-compose build and up

### ISSUE THREAD

**Issue by neelabalan** [danionescu0/docker-flask-mongodb-example#59]
Hi. I am working on testing this workflow in my private repos. What do you think? 

[reference](https://github.com/sonufrienko/microservice/blob/master/.github/workflows/test-integration.yml)

**Comment by danionescu0** [comment]
I've heard about github workflows and looked up a tutorial once for 15 minutes but i haven't fully understood how it works. I'll leave it up to you for now. Do you have a simple tutorial for me ? thanks

**Comment by neelabalan** [comment]
yeah. Initially I referred to the github docs https://docs.github.com/en/actions/guides/building-and-testing-python
and started experimenting with them in my private repos.

**Comment by neelabalan** [comment]
I've tested this github action in my private repo and here is what I've added to make it all come together

`docker-compose.yml`
```yml
    web-test:
        image: alpine 
        depends_on:
            - web-base-image
            - web-random
            - web-random-pypy
            - web-users
            - background-mqtt
            - web-fulltext-search 
            - web-geolocation-search
            - web-baesian
            - web-photo-process
            - web-book-collection
            - web-users-fast-api
            - influxdb
            - grafana
            - mongo
            - mqtt
            - krakend
```

`.github/workflows/build.yml`
```yml
name: test-build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Test
        run: docker-compose build && docker-compose up --exit-code-from web-test 
```

It works well. I've tested it for various scenarious like the port collisions and incorrect commands. Let me know what you think. If you are planning for adding integration tests in the future then I think I can work on this combined with integration tests for some more time and raise a PR altogether.

> link I found for [integration test](https://blog.avenuecode.com/how-to-run-integration-tests-using-docker-compose-and-.net-5) with docker-compose
