### ISSUE TITLE
choosing a code formatter / style guide enforcer

### ISSUE THREAD

**Issue by neelabalan** [danionescu0/docker-flask-mongodb-example#65]

**Comment by neelabalan** [comment]
There are actually three python linting service autopep8, pylint and flake8

for flake8 we can have the following `.flake8` in root folder
```ini
[flake8]
max-complexity = 10
select = C,E,F,W,B
ignore = E201, E501, E202
```
Here you can find what rules can be ignored (https://www.flake8rules.com)

and for black the precommit hook will look like this and this is the only configuration we will ever need and rest is taken care of. We can also use the` --check` and `--diff` argument to fail the commit if it doesn't meet black's required standards.
```yml
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.8
```

autopep8 formats Python code to the PEP8 style. It fixes most of the formatting issues that are reported by pycodestyle

```ini
[pep8]
ignore = E226,E302,E41
max-line-length = 160
```

with yapf code formatting there is lot of options that can be set in config on how to format the code like
```ini

[style]
based_on_style = pep8
SPLIT_BEFORE_LOGICAL_OPERATOR = true
ARITHMETIC_PRECEDENCE_INDICATION = true
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = true
DEDENT_CLOSING_BRACKETS = true
```

Let me know with which one we can go ahead, I'll make those changes and raise a PR.

**Comment by danionescu0** [comment]
Hmm i'll check it out, i'm searching for articles like this: https://www.slant.co/versus/12630/12632/~pylint_vs_flake8

Meanwhile what is your opinion what would you like to use in the project ?

**Comment by neelabalan** [comment]
My opinion is that using black can be good since we can get inplace formatting done based on standard style guides with minimal config.

This doc has all put together in one place
https://books.agiliq.com/projects/essential-python-tools/en/latest/linters.html

**Comment by danionescu0** [comment]
Ok let's go with black it seems simple. After the first run we might change some code too :)

Thanks for coming up with new ideas to improve the tutorial they are great!

**Comment by neelabalan** [comment]
Thank you! I will try to raise a PR today with pre-commit and code changes.

**Comment by neelabalan** [comment]
### review before PR
There will be a `pre-commit-config.yaml` at root folder with following contents
```yml
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1 
    hooks:
      - id: black
        language_version: python3
```

`pre-commit install` to install the hooks

### adding github actions
(If you think we can use this I'll add this too in the PR)
`.github/workflows/link.yml`

```yml
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          args: "python/ tests/ --check"
```

I've tested all of this in my private repo. I can add a `CONTRIBUTIONS.md` with detailed steps for future contributors if required.
